[book]
title = "ThreeFold Knowledge Base"

[output.html.fold]
enable = true
level = 0

[output.html]
no-section-label = true
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[output.html.print]
enable = false

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"
