name: www2.anual.grid.tf
on:
  push:
    branch: [ development ]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: pushing latest change on www2.manual.grid.tf
      uses: appleboy/ssh-action@master
      with:
        host: www2.manual.grid.tf
        username: ${{ secrets.TF_USER }}
        key: ${{ secrets.TF_SECRET }}
        port: ${{ secrets.TF_PORT }}
        script: |
          cd ~/websites/www2/info_grid
          git log -1
          git pull
          source ~/.cargo/env
          mdbook build -d docs
